pet_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from core.views import index, about
from django.urls import path, include

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/services/', include('services.urls')),
    path('dashboard/medicalvisit/', include('medicalvisit.urls')),
    path('dashboard/appointments/', include('appointments.urls')),
    path('dashboard/chatbot/', include('chatbot.urls')),
    path('pets/', include('pets.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


   

pets/urls.py
from django.urls import path


from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.pets_list, name='list'),
    path('add-pet/', views.add_pet, name='add_pet'),
    path('<int:pet_id>/', views.pet_detail, name='detail'),
    path('<int:pet_id>/delete/', views.pet_delete, name='delete'),
    path('<int:pet_id>/edit/', views.pet_edit, name='edit'),
    path('add-weight/<int:pet_id>/', views.add_weight_record, name='add_weight_record'),
    path('<int:pet_id>/edit_goal_weight/', views.edit_goal_weight, name='edit_goal_weight'),
    path('pets/<int:record_id>/delete-weight-record/', views.delete_weight_record, name='delete_weight_record'),
    path('petowner/list/', views.petowner_list, name='petowner_list'),
    path('petowner/<int:petowner_id>/', views.petowner_detail, name='petowner_detail'),
    path('vetstaff/<int:vetstaff_id>/', views.vetstaff_detail, name='vetstaff_detail'),
    path('search/', views.search, name='search'),
    path('weight-tracker/', views.weighttracker, name='weight_tracker'),
]

pets/models.py
from django.conf import settings
from django.db import models




class MedicalHistory(models.Model):
    VACCINATED = 'vaccinated'
    ALLERGY = 'allergy'
    SURGERY = 'surgery'
    NONE = 'none'
    OTHER = 'other'
    CATEGORY_CHOICES = [
        (VACCINATED, 'Vaccinated'),
        (ALLERGY, 'Allergy'),
        (SURGERY, 'Surgery'),
        (NONE, 'None'),
        (OTHER, 'Other'),
    ]

    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, unique=True)

    def __str__(self):
        return self.get_category_display()


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    BIRD = 'bird'
    OTHER = 'other'

    SPECIES_CHOICES = [
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (BIRD, 'Bird'),
        (OTHER, 'Other'),
    ]

    # Define breeds for each species
    LABRADOR = 'labrador'
    GERMAN_SHEPHERD = 'German Shepherd'
    POODLE = 'Poodle'
    PERSIAN = 'persian'
    MAINE_CONN = 'Maine Coon'
    SIAMESE = 'Siamese'
    PARROT = 'parrot'

    # This dictionary is used for JavaScript logic in templates, not for Django model field
    BREED_CHOICES_DICT = {
        DOG: [(LABRADOR, 'Labrador'), (GERMAN_SHEPHERD, 'German Shepherd'), (POODLE, 'Poodle')],
        CAT: [(PERSIAN, 'Persian Cat'), (MAINE_CONN, 'Maine Coon'), (SIAMESE, 'Siamese')],
        BIRD: [(PARROT, 'Parrot')],
        OTHER: [(OTHER, 'Other')]
    }
    MALE = 'M'
    FEMALE = 'F'
    UNKNOWN = 'U'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (UNKNOWN, 'Unknown'),
    ]
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=UNKNOWN,
    )


    petowner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pets')
    name = models.CharField(max_length=50)
    species = models.CharField(max_length=30, choices=SPECIES_CHOICES, default=DOG)
    spayed_neutered = models.BooleanField(default=False)
    image = models.ImageField(upload_to='pet_app/', blank=True, null=True)
    breed = models.CharField(max_length=50)  # No default choices here
    age = models.IntegerField()
    medical_history = models.ManyToManyField('MedicalHistory', blank=True)

    def __str__(self):
        return f"{self.name} ({self.species}) ({self.petowner})"



class WeightRecord(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='weight_records')
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateField()
    goal_weight = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.pet.name} - {self.weight}Kgs on {self.date}"
    
    def to_goal_weight(self):
        if self.goal_weight is not None:
            return self.goal_weight - self.weight
        return None

pets/forms.py
from django import forms
from .models import Pet, WeightRecord, MedicalHistory



class PetOwnerForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'species', 'breed', 'age', 'medical_history', 'image', 'gender', 'spayed_neutered']
        widgets = {
            'medical_history': forms.CheckboxSelectMultiple(),
            'breed': forms.Select(),  
        }

    def __init__(self, *args, **kwargs):
        super(PetOwnerForm, self).__init__(*args, **kwargs)
        # Initialize species choices
        self.fields['species'].choices = Pet.SPECIES_CHOICES
        # Initially, breed choices are empty since they depend on species selection
        self.fields['breed'].choices = []

        # If editing an existing instance, pre-populate breeds based on species
        if 'instance' in kwargs and kwargs['instance']:
            species = kwargs['instance'].species
            self.fields['breed'].choices = Pet.BREED_CHOICES_DICT.get(species, [])


class WeightRecordPetInitialForm(forms.ModelForm):
    class Meta:
        model = WeightRecord
        fields = ['pet', 'weight', 'date', 'goal_weight', 'notes']  
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        pet = kwargs.pop('pet', None)
        super(WeightRecordPetInitialForm, self).__init__(*args, **kwargs)

        # Conditionally manipulate the 'pet' field if it exists
        if pet and 'pet' in self.fields:
            self.fields['pet'].queryset = Pet.objects.filter(id=pet.id)  # This sets the queryset to only include the specified pet, effectively "pre-selecting" it if the field is rendered
            self.fields['pet'].initial = pet  # Set initial value to the specific pet instance
            self.fields['pet'].widget = forms.HiddenInput()  # Hide the 'pet' field to not render it in the form

class WeightRecordPetForm(forms.ModelForm):
    class Meta:
        model = WeightRecord
        fields = ['pet', 'weight', 'date', 'notes']  # Ensure 'pet' is included if you intend to manipulate it
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        pet = kwargs.pop('pet', None)
        super(WeightRecordPetForm, self).__init__(*args, **kwargs)

        # Conditionally manipulate the 'pet' field if it exists
        if pet and 'pet' in self.fields:
            self.fields['pet'].queryset = Pet.objects.filter(id=pet.id)  # This sets the queryset to only include the specified pet, effectively "pre-selecting" it if the field is rendered
            self.fields['pet'].initial = pet  # Set initial value to the specific pet instance
            self.fields['pet'].widget = forms.HiddenInput()  # Hide the 'pet' field to not render it in the form

class GoalWeightForm(forms.ModelForm):
    class Meta:
        model = WeightRecord
        fields = ['goal_weight']


class MedicalHistoryForm(forms.ModelForm):
    class Meta:
        model = MedicalHistory
        fields = ['category']
        labels = {
            'category': 'Medical History Category',
        }
        help_texts = {
            'category': 'Select the appropriate category for the medical history record.',
        }
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

pets/views.py
import json
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from pet_app.decorators import vetstaff_required, petowner_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PetOwnerForm, WeightRecordPetForm, WeightRecordPetInitialForm, GoalWeightForm
from .models import WeightRecord
from .models import Pet
from userprofile.models import PetOwner, VetStaff



from .models import Pet


@login_required
def pets_list(request):

    if request.user.is_vetstaff:
        pets_queryset = Pet.objects.prefetch_related('medical_history')
    else:
        pets_queryset = Pet.objects.filter(petowner=request.user).prefetch_related('medical_history')
    
    # Custom serialization
    pets_data = []
    for pet in pets_queryset:
        pet_data = {
            'id': pet.id,
            'name': pet.name,
            'species': pet.species,
            'breed': pet.breed,
            'age': pet.age,
            'image_url': pet.image.url if pet.image else '',
            'gender':pet.gender,
            'spayed_neutered': 'Yes' if pet.spayed_neutered else 'No',
            'medical_history': [str(history) for history in pet.medical_history.all()]
        }
        pets_data.append(pet_data)

    pets_json = json.dumps(pets_data)  

    return render(request, 'pets/pets_list.html', {'pets': pets_json})


@login_required
def pet_delete(request, pet_id):
    pet = get_object_or_404(Pet, petowner=request.user, pk=pet_id)
    pet.delete()
    messages.success(request, "The pet was deleted")

    return redirect('pets:list')


@login_required
def pet_edit(request, pet_id):
    pet = get_object_or_404(Pet, petowner=request.user, pk=pet_id)

    if request.method == 'POST':
        form = PetOwnerForm(request.POST, instance=pet)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.petowner = request.user
            pet.save()
            form.save_m2m() 
            messages.success(request, "The pet information was edited")
            return redirect('pets:list')
    else:
        form = PetOwnerForm(instance=pet)  
    
    breed_choices_dict = Pet.BREED_CHOICES_DICT
    breed_choices_json = json.dumps(breed_choices_dict)
    
    return render(request, 'pets/edit_mypet.html', {
        'form': form,
        'breed_choices_json': breed_choices_json  
    })


@login_required
def add_pet(request):
    if request.method == 'POST':
        form = PetOwnerForm(request.POST, request.FILES)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.petowner = request.user
            pet.save()
            form.save_m2m()  # Save the many-to-many data for 'medical_history'
            messages.success(request, "The pet was successfully added.")
            return redirect('pets:list')
    else:
        form = PetOwnerForm()

    breed_choices_dict = Pet.BREED_CHOICES_DICT
    breed_choices_json = json.dumps(breed_choices_dict)
    return render(request, 'pets/add_pet.html', {
        'form': form,
        'breed_choices_json': breed_choices_json  
    })


@login_required
def pet_detail(request, pet_id):
    # Fetch pet details, ensuring it's owned by the logged-in user or accessible by vet staff
    if request.user.is_vetstaff:
        pet = get_object_or_404(Pet, id=pet_id)
    else:
        pet = get_object_or_404(Pet, id=pet_id, petowner=request.user)

    # Fetch weight records for the pet
    records = WeightRecord.objects.filter(pet=pet).order_by('-date')

    # Preparing the data for the graph
    dates = [record.date.strftime("%Y-%m-%d") for record in records]
    weights = [float(record.weight) for record in records]
    goal_weights = [float(record.goal_weight) for record in records if record.goal_weight]

    # Assuming the most recent record contains the current weight and goal weight
    if records:
        current_weight = weights[0]  # Most recent weight due to '-date' ordering
        goal_weight = goal_weights[0] if goal_weights else None  # Most recent goal weight, if available
        to_goal_weight = current_weight - goal_weight if goal_weight is not None else None
    else:
        current_weight, goal_weight, to_goal_weight = None, None, None

    # Serialize data for safe JavaScript use
    dates_json = json.dumps(dates)
    weights_json = json.dumps(weights)
    goal_weights_json = json.dumps(goal_weights)

    return render(request, 'pets/detail_pet.html', {
        'pet': pet,
        'records': records,
        'dates_json': dates_json,
        'weights_json': weights_json,
        'goal_weights_json': goal_weights_json,
        'current_weight': current_weight,
        'goal_weight': goal_weight,
        'to_goal_weight': to_goal_weight,
    })


@login_required
def edit_goal_weight(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id, petowner=request.user)  # Ensure the pet belongs to the user
    weight_record = WeightRecord.objects.filter(pet=pet).order_by('-date').first()  # Get the most recent record

    if request.method == 'POST':
        form = GoalWeightForm(request.POST, instance=weight_record)
        if form.is_valid():
            form.save()
            return redirect('pets:detail', pet_id=pet.id)
    else:
        form = GoalWeightForm(instance=weight_record)  # Pass the most recent record to prepopulate the form

    return render(request, 'pets/edit_goal_weight.html', {
        'form': form,
        'pet': pet
    })
    
@login_required
def add_weight_record(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id, petowner=request.user)  # Adjusted to use 'petowner' instead of 'owner'

    # Check if this is the first weight record for the pet
    first_record = not WeightRecord.objects.filter(pet=pet).exists()

    if request.method == 'POST':
        # Use the initial form if this is the first weight record, else use the regular form
        if first_record:
            form = WeightRecordPetInitialForm(request.POST, pet=pet)
        else:
            form = WeightRecordPetForm(request.POST, pet=pet)
        
        if form.is_valid():
            weight_record = form.save(commit=False)
            weight_record.pet = pet
            weight_record.save()
            messages.success(request, "Weight record added successfully.")
            return redirect('pets:detail', pet_id=pet.id)
    else:
        # Initialize the appropriate form based on whether it's the first record
        if first_record:
            form = WeightRecordPetInitialForm(pet=pet)  # Create form instance with pet
        else:
            form = WeightRecordPetForm(pet=pet)  # Create form instance with pet

    return render(request, 'pets/add_weight_record.html', {'form': form, 'pet': pet})


@login_required
def delete_weight_record(request, record_id):
    record = get_object_or_404(WeightRecord, pk=record_id, pet__petowner=request.user)
    record.delete()
    messages.success(request, "The weight record was deleted successfully.")
    return redirect('pets:detail', pet_id=record.pet.id)



@login_required
def weighttracker(request):
    pets = Pet.objects.filter(petowner=request.user)
    return render(request, 'pets/weight_tracker.html', {'pets': pets})

@login_required
def petowner_detail(request, petowner_id):
   
    petowner = get_object_or_404(PetOwner, pk=petowner_id)
    
    pets = Pet.objects.filter(petowner__id=petowner_id)

    context = {
        'petowner': petowner, 
        'pets': pets
    }
    return render(request, 'pets/petowner_detail.html', context)

@login_required
def vetstaff_detail(request, vetstaff_id):
    vetstaff = get_object_or_404(VetStaff, pk=vetstaff_id)

    context = {
        'vetstaff': vetstaff,  
    }
    return render(request, 'pets/vetstaff_detail.html', context)

@login_required
def petowner_list(request):
    petowners = PetOwner.objects.all()

    context = {
        'petowners': petowners, 
    }
    return render(request, 'pets/petowner_list.html', context)




@login_required
def search(request):
    query = request.GET.get('query', '')
    petowners = PetOwner.objects.none()
    pets = Pet.objects.none()
    vetstaff = VetStaff.objects.none()

    user = request.user

    # Utilize the custom boolean fields in your User model for role determination
    if user.is_vetstaff:
        # Vet staff search logic for petowners and pets
        petowners = PetOwner.objects.filter(
            Q(user__username__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
        pets = Pet.objects.filter(name__icontains=query).distinct()

    elif user.is_petowner:
        # Pet owner search logic for vetstaff
        vetstaff = VetStaff.objects.filter(
            Q(user__username__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

    context = {
        'petowners': petowners,
        'pets': pets,
        'vetstaff': vetstaff,
        'query': query
    }

    return render(request, 'pets/search_results.html', context)

pets/templates/pets/detail_pet.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}
<div class="w-full h-full p-16 flex justify-center bg-white">
    <div class="container w-full p-16 flex flex-col items-center justify-center">
        <div class="w-full pb-2 flex">
            <div
                class="w-full flex flex-col items-center justify-center">
                <a href="{% url 'pets:detail' pet.id %}">
                    <div class="w-full flex pt-20 pr-2">
                        <div class="w-[40%] flex pr-2">
                            {% if pet.image %}
                            <!-- If there's an image, use it -->
                            <img src="{{ pet.image.url }}" alt="Image of {{ pet.name }}"
                                class="mb-4 rounded-lg shadow-lg"
                                style="height:250px; width: 250px; object-fit: cover;">
                            {% else %}
                            <!-- Otherwise, use a default image -->
                            <img src="{% static 'pet_app/2chf_800.jpg' %}" alt="Default profile picture"
                                class="mb-4 rounded-lg shadow-lg"
                                style="height:250px; width: 250px; object-fit: cover;">
                            {% endif %}
                        </div>
                        <div class="w-[60%] flex flex-col pl-2">
                            <div class="w-full py-1 flex border-b border-slate-300">
                                <h1 class="flex text-2xl font-bold p-6 px-1 pt-1">{{ pet.name }}</h1>
                            </div>
                            <div class="w-full pt-4 flex flex-col lg:flex-row lg:flex-wrap">
                                <div class="flex flex-col p-1">
                                    <p class="p-2 text-md text-gray-700"><strong>Species:</strong> {{pet.species}}</p>
                                    <p class="p-2 text-md text-gray-700"><strong>Breed:</strong> {{pet.breed}}</p>
                                </div>
                                <div class="flex flex-col p-1">
                                    <p class="p-2 text-md text-gray-700"><strong>Age:</strong> {{pet.age}}</p>
                                    <p class="p-2 text-md text-gray-700"><strong>Gender:</strong> {{pet.gender}}</p>
                                    <p class="p-2 text-md text-gray-700"><strong>Spayed or
                                            Neutered:</strong>{{pet.spayed_neutered}}</p>
                                </div>
                                <div class="flex flex-col p-4 items-center justify-center">
                                    <h2 class="text-xl font-semibold mb-2">Medical History</h2>
                                    <ul class="list-disc pl-5 text-gray-600">
                                        {% for history in pet.medical_history.all %}
                                        <li>{{ history }}</li>
                                        {% empty %}
                                        <li class="text-gray-500 italic">No medical history records available.</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% if request.user.is_petowner %}
                <div class="flex flex-row p-2">
                    <div class="flex p-6">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'pets:add_weight_record' pet.id %}" class="w-full flex flex-row justify-center
                        items-center">
                                    Add New Weight
                                </a>
                            </span>
                        </button>
                    </div>
                    <div class="flex p-6">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'pets:edit' pet.id %}" class="w-full flex flex-row justify-center
                    items-center">
                                    Edit Your Pet Profile
                                </a>
                            </span>
                        </button>
                    </div>
                    <div class="flex p-6">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'pets:delete' pet.id %}" class="w-full flex flex-row justify-center
                    items-center">
                                    Delete Your Pet Profile
                                </a>
                            </span>
                        </button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% if records %}
        <div class="w-full pt-2 flex flex-row justify-between">
            <div class="w-[35%] pr-2 flex">
                <div class="w-full p-10 flex flex-col items-center bg-white shadow-lg rounded-lg">
                    <h1 class="text-xl font-semibold text-gray-800 mb-4">Pet Weight Overview</h1>
                    <!-- Displaying Current Weight, Goal Weight, and To Goal Weight -->
                    <div class="mt-4 space-y-6">
                        <div class="text-base font-semibold">Current Weight: <span class="text-gray-800">{{ current_weight }}
                            Kgs</span></div>
                        <div class="text-base font-semibold">Goal Weight: <span class="text-gray-800">{{ goal_weight }}
                            Kgs</span></div>
                        <div class="text-base font-semibold">To Goal Weight: <span class="text-gray-800">{{ to_goal_weight }}
                            Kgs</span></div>
                    </div>
                    {% if request.user.is_petowner %}
                    <div class="flex p-6">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'pets:edit_goal_weight' pet.id %}" class="w-full flex flex-row justify-center items-center">
                                    Edit goal weight
                                </a>
                            </span>
                        </button>
                    </div>
                    {% endif %}
                </div>
            </div>
            <!-- Chart.js Graph -->
            <div class="w-[75%] pl-2 flex">
                <div class="w-full p-10 flex  bg-white shadow-lg rounded-lg">
                    <div class="w-full relative size-full">
                        <!-- h-64 is an arbitrary height, you can adjust as needed -->
                        <canvas id="weightChart"></canvas>
                    </div>
                    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                    <script>
                        const dates = JSON.parse('{{ dates_json|safe }}');
                        const weights = JSON.parse('{{ weights_json|safe }}');
                        const goalWeights = JSON.parse('{{ goal_weights_json|safe }}');

                        const ctx = document.getElementById('weightChart').getContext('2d');
                        const weightChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: dates,
                                datasets: [{
                                    label: 'Weight',
                                    data: weights,
                                    backgroundColor: 'rgba(75, 192, 192, 0.2)', // Light teal with some transparency
                                    borderColor: 'rgb(75, 192, 192)', // Solid teal
                                    borderWidth: 1,
                                    yAxisID: 'y',
                                },
                                {
                                    label: 'Goal Weight',
                                    data: goalWeights,
                                    backgroundColor: 'rgba(192, 75, 75, 0.2)', // Light red with some transparency
                                    borderColor: 'rgb(192, 75, 75)', // Solid red
                                    borderWidth: 1,
                                    yAxisID: 'y1',
                                }]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true,
                                        position: 'left',
                                    },
                                    y1: {
                                        beginAtZero: true,
                                        position: 'right',
                                        grid: {
                                            drawOnChartArea: false, // Only want the grid lines for one axis to show up
                                        },
                                    },
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
        {% else %}
        {% endif %}
    </div>
</div>

{% endblock %}

pets/templates/pets/edit_goal_weight.html
{% extends 'core/base.html' %}

{% block content %}
<!-- Weight Records -->
<div class="w-full h-screen p-32 flex items-center justify-center bg-white">
    <div class="container w-[60%] p-8 flex flex-col">
        <h2 class="font-semibold">Edit Goal Weight for {{ pet.name }}</h2>
        <form class="flex flex-col p-8" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="flex flex-col p-8 items-center justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        Save changes
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

pets/templates/pets/search_results.html
{% extends 'core/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
{% load static %}
<div class="w-full h-screen p-16 flex flex-col justify-center items-center bg-white">
    <div class="w-full h-full flex flex-col justify-center items-center space-y-8">
        <h2 class="text-2xl font-bold text-center text-gray-800">Search Results</h2>
        
        {% if petowners %}
        <div>
            <h3 class="text-xl font-semibold text-gray-800">Pet Owners</h3>
            <ul class="list-disc list-inside">
                {% for petowner in petowners %}
                <li class="text-gray-600 p-8">
                    <a href="{% url 'pets:petowner_detail' petowner.user.id %}">{{ petowner.user.get_full_name }}</a>
                    {% if petowner.pets %}
                    <ul class="ml-4 list-disc list-inside p-8">
                        {% for pet in petowner.pets %}
                        <li class="text-gray-500 p-2">
                            <a href="{% url 'pets:detail' pet.id %}" class="text-blue-500 hover:text-blue-600">{{ pet.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p class="ml-4 text-gray-500">No pets found for this owner.</p>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% if vetstaff %}
        <div>
            <h3 class="text-xl font-semibold text-gray-800">Vet Staff</h3>
            <ul class="list-disc list-inside">
                {% for vet in vetstaff %}
                <li class="text-gray-600 p-8">
                    <a href="{% url 'pets:vetstaff_detail' vet.user.id %}">{{ vet.user.get_full_name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% if not petowners and not vetstaff %}
        <p class="text-gray-600">No results found for "{{ query }}"</p>
        {% endif %}
    </div>
</div>

{% endblock %}