appointments/urls.py
from django.urls import path


from . import views

app_name = 'appointments'

urlpatterns = [
    path('add-schedule/<int:service_id>/', views.schedule_appointment_view, name='add_schedule'),
    path('cancel-appointment/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('available-slots/', views.available_slots, name='available_slots'),
    path('appointments-list/', views.view_appointments, name='appointments_list'),
    path('create-slot/', views.create_slot_view, name='create_slot'),
    path('delete-slot/<int:appointmentslot_id>/', views.delete_slots, name='delete_slot'),
    path('slots/', views.slots_view, name='slots_view'),
]

pet_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from core.views import index, about
from django.urls import path, include

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/services/', include('services.urls')),
    path('dashboard/medicalvisit/', include('medicalvisit.urls')),
    path('dashboard/appointments/', include('appointments.urls')),
    path('dashboard/chatbot/', include('chatbot.urls')),
    path('pets/', include('pets.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


   

pets/urls.py
from django.urls import path


from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.pets_list, name='list'),
    path('add-pet/', views.add_pet, name='add_pet'),
    path('<int:pet_id>/', views.pet_detail, name='detail'),
    path('<int:pet_id>/delete/', views.pet_delete, name='delete'),
    path('<int:pet_id>/edit/', views.pet_edit, name='edit'),
    path('add-weight/<int:pet_id>/', views.add_weight_record, name='add_weight_record'),
    path('<int:pet_id>/edit_goal_weight/', views.edit_goal_weight, name='edit_goal_weight'),
    path('pets/<int:record_id>/delete-weight-record/', views.delete_weight_record, name='delete_weight_record'),
    path('petowner/list/', views.petowner_list, name='petowner_list'),
    path('petowner/<int:petowner_id>/', views.petowner_detail, name='petowner_detail'),
    path('vetstaff/<int:vetstaff_id>/', views.vetstaff_detail, name='vetstaff_detail'),
    path('search/', views.search, name='search'),
    path('weight-tracker/', views.weighttracker, name='weight_tracker'),
]

appointments/models.py
import logging
from django.db import transaction
from django.db import models
from pets.models import Pet
from userprofile.models import User
from services.models import PetRequestService, PetService

logger = logging.getLogger(__name__)

class AppointmentSlot(models.Model):
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    is_booked = models.BooleanField(default=False)
    vet_staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    service_type = models.ForeignKey(PetService, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.date} {self.start_time}-{self.end_time}"
    
from datetime import datetime

def get_available_slots(date, service_id=None):
    logger.debug(f"get_available_slots called with date: {date}, service_id: {service_id}")
    # Check if the date argument is a string and convert it to a datetime.date object
    if isinstance(date, str):
        try:
            date = datetime.strptime(date, '%Y-%m-%d').date()
        except ValueError:
            print("Invalid date format. Date should be in 'YYYY-MM-DD' format.")
            return AppointmentSlot.objects.none()
    
    # If the date is already a datetime.date object, use it directly in the query
    query = AppointmentSlot.objects.filter(date=date, is_booked=False)
    if service_id is not None:
        query = query.filter(service_type_id=service_id)

    return query

    
def is_slot_overlapping(date, start_time, end_time, vet_staff_id):
    overlapping_slots = AppointmentSlot.objects.filter(
        date=date,
        vet_staff_id=vet_staff_id,
        end_time__gt=start_time,  
        start_time__lt=end_time   
    ).exists()

    return overlapping_slots


def is_slot_available(slot_id):
    return not AppointmentSlot.objects.filter(id=slot_id, is_booked=True).exists()

def book_slot(slot_id):
    with transaction.atomic():
        slot = AppointmentSlot.objects.select_for_update().get(id=slot_id)
        if slot.is_booked:
            raise ValueError("Slot is already booked")
        slot.is_booked = True
        slot.save()


class Appointment(models.Model):
    petowner = models.ForeignKey(User, on_delete=models.CASCADE)
    pet_request_service = models.ForeignKey(PetRequestService, on_delete=models.PROTECT, related_name='appointments')
    slot = models.ForeignKey(AppointmentSlot, on_delete=models.CASCADE, related_name='appointments')
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Appointment for {self.pet.name} - {self.pet_request_service} on {self.slot.date} {self.slot.start_time}-{self.slot.end_time}"

pets/models.py
from django.conf import settings
from django.db import models




class MedicalHistory(models.Model):
    VACCINATED = 'vaccinated'
    ALLERGY = 'allergy'
    SURGERY = 'surgery'
    NONE = 'none'
    OTHER = 'other'
    CATEGORY_CHOICES = [
        (VACCINATED, 'Vaccinated'),
        (ALLERGY, 'Allergy'),
        (SURGERY, 'Surgery'),
        (NONE, 'None'),
        (OTHER, 'Other'),
    ]

    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, unique=True)

    def __str__(self):
        return self.get_category_display()


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    BIRD = 'bird'
    OTHER = 'other'

    SPECIES_CHOICES = [
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (BIRD, 'Bird'),
        (OTHER, 'Other'),
    ]

    # Define breeds for each species
    LABRADOR = 'labrador'
    GERMAN_SHEPHERD = 'German Shepherd'
    POODLE = 'Poodle'
    PERSIAN = 'persian'
    MAINE_CONN = 'Maine Coon'
    SIAMESE = 'Siamese'
    PARROT = 'parrot'

    # This dictionary is used for JavaScript logic in templates, not for Django model field
    BREED_CHOICES_DICT = {
        DOG: [(LABRADOR, 'Labrador'), (GERMAN_SHEPHERD, 'German Shepherd'), (POODLE, 'Poodle')],
        CAT: [(PERSIAN, 'Persian Cat'), (MAINE_CONN, 'Maine Coon'), (SIAMESE, 'Siamese')],
        BIRD: [(PARROT, 'Parrot')],
        OTHER: [(OTHER, 'Other')]
    }
    MALE = 'M'
    FEMALE = 'F'
    UNKNOWN = 'U'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (UNKNOWN, 'Unknown'),
    ]
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=UNKNOWN,
    )


    petowner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pets')
    name = models.CharField(max_length=50)
    species = models.CharField(max_length=30, choices=SPECIES_CHOICES, default=DOG)
    spayed_neutered = models.BooleanField(default=False)
    image = models.ImageField(upload_to='pet_app/', blank=True, null=True)
    breed = models.CharField(max_length=50)  # No default choices here
    age = models.IntegerField()
    medical_history = models.ManyToManyField('MedicalHistory', blank=True)

    def __str__(self):
        return f"{self.name} ({self.species}) ({self.petowner})"



class WeightRecord(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='weight_records')
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateField()
    goal_weight = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.pet.name} - {self.weight}Kgs on {self.date}"
    
    def to_goal_weight(self):
        if self.goal_weight is not None:
            return self.goal_weight - self.weight
        return None

appointments/forms.py
# appointments/forms.py
from django import forms
from django.forms.widgets import DateInput, TimeInput
from .models import Appointment, AppointmentSlot
from pets.models import Pet
from userprofile.models import User
from services.models import PetRequestService



class AppointmentForm(forms.ModelForm):
    slot = forms.ModelChoiceField(queryset=AppointmentSlot.objects.none(), required=True)

    class Meta:
        model = Appointment
        fields = ['pet_request_service', 'slot', 'notes']  

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        service_request = kwargs.pop('service_request', None)
        super(AppointmentForm, self).__init__(*args, **kwargs)

        if user:
            # Filter the pet_request_service queryset to only include services requested by this user
            self.fields['pet_request_service'].queryset = PetRequestService.objects.filter(petowner=user)

            # If a specific service request is provided, set it as the initial value and filter slots accordingly
            if service_request:
                self.fields['pet_request_service'].initial = service_request
                self.fields['slot'].queryset = AppointmentSlot.objects.filter(
                    service_type=service_request.service, is_booked=False)
                





class SlotCreationForm(forms.ModelForm):
    class Meta:
        model = AppointmentSlot
        fields = ['date', 'start_time', 'end_time', 'vet_staff', 'service_type']
        widgets = {
            'date': DateInput(attrs={'type': 'date', 'class': 'mt-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300'}),
            'start_time': TimeInput(attrs={'type': 'time', 'class': 'mt-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300'}),
            'end_time': TimeInput(attrs={'type': 'time', 'class': 'mt-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(SlotCreationForm, self).__init__(*args, **kwargs)
        if user and user.is_vetstaff:
            self.fields['vet_staff'].queryset = User.objects.filter(is_vetstaff=True)

appointments/views.py
import datetime
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from pet_app.decorators import vetstaff_required
from .forms import AppointmentForm, SlotCreationForm
from services.models import PetRequestService
from pets.models import Pet
from userprofile.models import Notification, User
from .models import Appointment, AppointmentSlot, book_slot, is_slot_available, get_available_slots


@login_required
def schedule_appointment_view(request, service_id):
    service_request = get_object_or_404(PetRequestService, id=service_id)
    user = request.user
    available_slots = []

    if request.method == 'POST':
        appointment_form = AppointmentForm(request.POST, user=user, service_request=service_request)

        if appointment_form.is_valid():
            selected_slot_id = appointment_form.cleaned_data.get('slot').id  # Retrieve slot ID from form data
            if is_slot_available(selected_slot_id):
                appointment = appointment_form.save(commit=False)
                appointment.service = service_request
                appointment.petowner = user
                appointment.save()
                book_slot(selected_slot_id)
                return redirect('services:payment')
            else:
                messages.error(request, "Selected slot is no longer available.")
    else:
        appointment_form = AppointmentForm(user=user, service_request=service_request)
        # If a GET request, initialize the slot queryset
        appointment_form.fields['slot'].queryset = AppointmentSlot.objects.filter(
            service_type=service_request.service, is_booked=False)
        available_slots = appointment_form.fields['slot'].queryset

    context = {
        'form': appointment_form,
        'available_slots': available_slots,  
        'service': service_request,
    }

    return render(request, 'appointments/schedule_appointment.html', context)




@login_required
def available_slots(request):
    selected_date = request.GET.get('date')
    service_id = request.GET.get('service_id', None)

    # Ensure selected_date is a string in the correct format
    if selected_date:
        try:
            # Attempt to convert selected_date to a date object and back to a string
            # This is to validate that selected_date is in the correct format
            #valid_date = datetime.date.fromisoformat(selected_date).isoformat()
            slots = get_available_slots(service_id)
        except ValueError:
            # Handle the case where selected_date is not in the correct format
            return JsonResponse({'error': 'Invalid date format'}, status=400)
    else:
        return JsonResponse({'error': 'No date provided'}, status=400)

    slots_data = [
        {
            "id": slot.id,
            "start_time": f"{slot.date} {slot.start_time.strftime('%H:%M')}",
            "end_time": f"{slot.date} {slot.end_time.strftime('%H:%M')}"
        } 
        for slot in slots
    ]
    print("Selected Date:", selected_date, type(selected_date))
    return JsonResponse(slots_data, safe=False)





@login_required
def cancel_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id, petowner=request.user)

    # Check if the appointment belongs to the logged-in user
    if appointment.petowner != request.user:
        messages.error(request, "You do not have permission to cancel this appointment.")
        return redirect('dashboard:dashboard')

    # Unbook the slot
    slot = appointment.slot
    slot.is_booked = False
    slot.save()

    # Delete or update the appointment as per your requirement

    appointment.delete()

    # For updating (e.g., setting a 'cancelled' flag):
    # appointment.save()

    messages.success(request, "Your appointment has been successfully cancelled.")
    return redirect('dashboard:dashboard') 



@login_required 
def create_slot_view(request):
    if request.method == 'POST':
        form = SlotCreationForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('dashboard:dashboard')  
    else:
        form = SlotCreationForm(user=request.user)

    return render(request, 'appointments/create_slot.html', {'form': form})



@vetstaff_required 
def slots_view(request):
    slots_appointments = AppointmentSlot.objects.all()

    return render(request, 'appointments/slots_appointments.html', {'slots_appointments': slots_appointments})


@vetstaff_required 
def delete_slots(request, appointmentslot_id):
    try:
        slot_appointment = AppointmentSlot.objects.get(id=appointmentslot_id)

        # Check if the slot is booked before deleting
        if slot_appointment.is_booked:
            slot_appointment.is_booked = False
            slot_appointment.save()  # Save the changes to the slot appointment

        slot_appointment.delete()  # Delete the slot appointment

        messages.success(request, "Appointment slot successfully deleted.")
    except AppointmentSlot.DoesNotExist:
        messages.error(request, "Appointment slot not found.")

    # Redirect to a view that lists all slots, or to another appropriate page
    return redirect('appointments:slots_view')  



@login_required
def view_appointments(request):
    user = request.user
    if user.is_vetstaff:
        appointments = Appointment.objects.select_related('petowner').all()
    else:
        appointments = Appointment.objects.filter(
            petowner=request.user
        ).select_related('slot').order_by('slot__date')

    return render(request, 'appointments/view_appointments.html', {'appointments': appointments})

appointments/templates/appointments/create_slot.html
{% extends 'core/base.html' %}

{% block title %} Create a Slot Appointment {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-screen p-16 flex justify-center bg-white">
    <div class="container w-[70%] my-8 p-6">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">Create Appointment Slot</h2>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="text-gray-700 font-medium">{{ field.label }}</label>
                {{ field|add_class:"mt-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300" }}
                {% if field.errors %}
                <span class="text-red-500 text-xs">{{ field.errors }}</span>
                {% endif %}
            </div>
            {% endfor %}
            <div class="flex p-3 items-center justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        Create slots
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const startTimeInput = document.querySelector('input[name="start_time"]');
        const endTimeInput = document.querySelector('input[name="end_time"]');

        function validateTime() {
            if (startTimeInput.value && endTimeInput.value) {
                if (endTimeInput.value <= startTimeInput.value) {
                    alert('End time must be after start time.');
                    endTimeInput.value = ""; // Clear end time if it's invalid
                }
            }
        }

        startTimeInput.addEventListener('change', validateTime);
        endTimeInput.addEventListener('change', validateTime);
    });
</script>
{% endblock %}

appointments/templates/appointments/schedule_appointment.html
{% extends 'core/base.html' %}

{% block title %} Schedule Appointment {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-full p-32 flex justify-center">
    <div class="container w-[70%] p-10 bg-white shadow-md rounded-lg">
        <h1 class="text-2xl font-bold mb-6">Schedule Your Appointment</h1>
        <form method="post" enctype="multipart/form-data" action=".">
            {% csrf_token %}

            <!-- Date Picker for Appointment Date -->
            <div class="mb-4">
                {% for field in form %}
                {% if field.is_hidden %}
                {{ field }}
                {% else %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field|add_class:"shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                    {% if field.errors %}
                    <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                    {% endif %}
                </div>
                {% endif %}
                {% endfor %}
            </div>

            <div class="flex items-center justify-center">
                <button type="submit"
                    class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row justify-center items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        Schedule Appointment
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>


<script>
    document.getElementById('appointment_date').addEventListener('change', function () {
        const selectedDate = this.value;
        axios.get(`{% url 'appointments:available_slots' %}`, {
            params: { date: selectedDate, service_id: "{{ service.id }}" }
        })
            .then(function (response) {
                console.log(response.data);
                const slotSelect = document.getElementById('id_slot'); // Corrected ID
                slotSelect.innerHTML = '';
                response.data.forEach(function (slot) {
                    slotSelect.options[slotSelect.options.length] = new Option(slot.start_time + ' - ' + slot.end_time, slot.id);
                });
            })
            .catch(function (error) {
                console.log(error);
                // Handle errors here, such as displaying a message to the user
            });
    });
</script>


{% endblock %}

appointments/templates/appointments/slots_appointments.html
{% extends 'core/base.html' %}

{% block title %} Slots Appointments {% endblock %}

{% block content %}
<div class="w-full h-full p-16 flex justify-center bg-white">
    <div class="container w-[75%] p-6 flex flex-col">
        <div class="flex flex-row items-center justify-between">
            <h1 class="flex text-2xl font-semibold text-gray-800 mb-4">Appointment Slots</h1>
            <div class="flex p-3 items-center justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        <a href="/dashboard/appointments/create-slot/">
                            Create slots
                        </a>
                    </span>
                </button>
            </div>
        </div>

        <div class="flex  flex-col p-10 overflow-hidden">
            <ul class="divide-y divide-gray-200">
                {% for slot in slots_appointments %}
                <li class="p-4 hover:bg-gray-50">
                    <p><span class="font-semibold">Date:</span> {{ slot.date }}</p>
                    <p><span class="font-semibold">Start Time:</span> {{ slot.start_time }}</p>
                    <p><span class="font-semibold">End Time:</span> {{ slot.end_time }}</p>
                    <p><span class="font-semibold">Booked:</span> {{ slot.is_booked }}</p>
                    <p><span class="font-semibold">Vet Staff:</span> {{ slot.vet_staff }}</p>
                    <p><span class="font-semibold">Service Type:</span> {{ slot.service_type }}</p>
                    <div class="flex p-3 items-center justify-center">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'appointments:delete_slot' slot.id %}">Delete</a>
                            </span>
                        </button>
                    </div>
                </li>
                {% empty %}
                <li class="text-gray-700">No appointment slots available.</li>
                <div class="flex p-3 items-center justify-center">
                    <button
                        class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                        <span
                            class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                            <a href="/dashboard/appointments/create-slot/">
                                Create slots
                            </a>
                        </span>
                    </button>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

appointments/templates/appointments/view_appointments.html
{% extends 'core/base.html' %}

{% block title %} Your Pet's Appointments {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-screen p-16 flex justify-center bg-white">
    <div class="container w-[75%] p-6 flex flex-col">
        {% if request.user.is_petowner %}
        <h2 class="text-2xl font-bold mb-4">Your Appointments</h2>
        {% else %}
        <h2 class="text-2xl font-bold mb-4">Appointments Pets</h2>
        {% endif %}

        {% if appointments %}
        <div class="flex  flex-col p-10 overflow-hidden">
            <ul class="divide-y divide-gray-200">
                {% for appointment in appointments %}
                <li class="p-4 hover:bg-gray-50">
                    <div class="flex items-center justify-between">
                        <div class="flex flex-col p-4">
                            <p class="p-1 font-semibold">{{ appointment.pet.name }}</p>
                            <p class="p-1  text-lg font-semibold">{{ appointment.pet_request_service }}</p>
                            <p class="p-1  text-gray-600">
                                {{ appointment.slot.date|date:"Y-m-d" }}
                                {{ appointment.slot.start_time|time:"H:i" }} - {{ appointment.slot.end_time|time:"H:i" }}
                                {{ appointment.service.get_name_display }}
                            </p>
                            {% if request.user.is_petowner %}
                            <div class="">
                                <button
                                    class="h-fit p-[2px] flex flex-row items-center justify-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                                    <span
                                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                        <a href="{% url 'appointments:cancel_appointment' appointment.id %}">Cancel
                                            Appointment</a>
                                    </span>
                                </button>
                            </div>
                            {% endif %}
                            {% if appointment.notes %}
                            <p class="text-gray-600 mt-2">Notes: {{ appointment.notes }}</p>
                            {% endif %}
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% else %}
        <p class="text-gray-600">No appointments found.</p>
        {% endif %}
    </div>
</div>


{% endblock %}