medicalvisit/urls.py
from django.urls import path


from . import views

app_name = 'medicalvisit'

urlpatterns = [
    path('add-medical-visit/', views.add_medical_visit, name='medical_visit'),
    path('add-medical-history/', views.add_medical_history, name='add_medical_history'),
    path('medical-visit-list/', views.medical_visit_list, name='medical_visit_list'),
    path('medical-visit/<int:medical_visit_id>/', views.medical_visit_detail, name='medical_visit_detail'),
    path('edit-medical-visit/<int:medical_visit_id>/', views.medical_visit_edit, name='edit_medical_visit'),
    path('<int:medical_visit_id>/delete/', views.medical_visit_delete, name='delete'),
]

pet_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from core.views import index, about
from django.urls import path, include

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/services/', include('services.urls')),
    path('dashboard/medicalvisit/', include('medicalvisit.urls')),
    path('dashboard/appointments/', include('appointments.urls')),
    path('dashboard/chatbot/', include('chatbot.urls')),
    path('pets/', include('pets.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


   

pets/urls.py
from django.urls import path


from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.pets_list, name='list'),
    path('add-pet/', views.add_pet, name='add_pet'),
    path('<int:pet_id>/', views.pet_detail, name='detail'),
    path('<int:pet_id>/delete/', views.pet_delete, name='delete'),
    path('<int:pet_id>/edit/', views.pet_edit, name='edit'),
    path('add-weight/<int:pet_id>/', views.add_weight_record, name='add_weight_record'),
    path('<int:pet_id>/edit_goal_weight/', views.edit_goal_weight, name='edit_goal_weight'),
    path('pets/<int:record_id>/delete-weight-record/', views.delete_weight_record, name='delete_weight_record'),
    path('petowner/list/', views.petowner_list, name='petowner_list'),
    path('petowner/<int:petowner_id>/', views.petowner_detail, name='petowner_detail'),
    path('vetstaff/<int:vetstaff_id>/', views.vetstaff_detail, name='vetstaff_detail'),
    path('search/', views.search, name='search'),
    path('weight-tracker/', views.weighttracker, name='weight_tracker'),
]

medicalvisit/models.py
from django.db import models
from django.conf import settings
from pets.models import Pet
from userprofile.models import User




class PetMedicalVisit(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='medical_visits')
    vet_staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='recorded_visits')
    date_of_visit = models.DateTimeField()
    symptoms = models.TextField()
    diagnosis = models.TextField()
    treatment = models.TextField()
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Medical Visit for {self.pet.name} of the petowner {self.pet.petowner} on {self.date_of_visit.strftime('%Y-%m-%d')}"

medicalvisit/forms.py
from django.forms.widgets import DateInput
from django import forms
from .models import PetMedicalVisit
from pets.models import Pet
from django.contrib.auth import get_user_model

User = get_user_model()



class PetMedicalVisitForm(forms.ModelForm):
    class Meta:
        model = PetMedicalVisit
        fields = ['pet', 'date_of_visit', 'symptoms', 'diagnosis', 'treatment', 'notes', 'vet_staff']
        widgets = {
            'date_of_visit': DateInput(attrs={'type': 'date', 'class': 'mt-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300'}),
            }

    def __init__(self, *args, **kwargs):
        pet_owner = kwargs.pop('petowner', None)
        super(PetMedicalVisitForm, self).__init__(*args, **kwargs)

        if pet_owner is not None:
            self.fields['pet'].queryset = Pet.objects.filter(petowner=pet_owner)

        self.fields['vet_staff'].queryset = User.objects.filter(is_vetstaff=True)

medicalvisit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from pet_app.decorators import vetstaff_required
from pets.forms import MedicalHistoryForm
from .forms import PetMedicalVisitForm
from .models import PetMedicalVisit


@vetstaff_required
def add_medical_visit(request):
    if request.method == 'POST':
        form = PetMedicalVisitForm(request.POST, request.FILES)
        if form.is_valid():
            medical_visit = form.save(commit=False)
            medical_visit.vet_staff = request.user
            medical_visit.save()
            messages.success(request, "The medical visit record saved successfully.")
            return redirect('medicalvisit:medical_visit_list')
    else:
        form = PetMedicalVisitForm()

    return render(request, 'medicalvisit/medicalvisitform.html', {'form': form})


@login_required
def medical_visit_list(request):
    user = request.user
    if user.is_vetstaff:
        medical_visits = PetMedicalVisit.objects.select_related('pet').all()
    
    else:
        medical_visits = PetMedicalVisit.objects.filter(pet__petowner=request.user).order_by('date_of_visit')
    
    return render(request, 'medicalvisit/recordsmedicalvisit.html', {'medical_visits': medical_visits})



@login_required
def medical_visit_detail(request, medical_visit_id):
    medical_visit = get_object_or_404(PetMedicalVisit, id=medical_visit_id)  
    return render(request, 'medicalvisit/medicalvisit_detail.html', {'medical_visit': medical_visit})
    


@vetstaff_required
def medical_visit_delete(request, medical_visit_id):
    medical_visit = get_object_or_404(PetMedicalVisit, pk=medical_visit_id)
    medical_visit.delete()
    messages.success(request, "The medical visit was deleted")

    return redirect('medicalvisit:medical_visit_list')


@vetstaff_required
def medical_visit_edit(request, medical_visit_id):
    medical_visit = get_object_or_404(PetMedicalVisit, pk=medical_visit_id)

    if request.method == 'POST':
        form = PetMedicalVisitForm(request.POST, request.FILES)
        if form.is_valid():
            medical_visit = form.save(commit=False)
            medical_visit.vet_staff = request.user
            medical_visit.save()
            messages.success(request, "The medical visit record saved edited successfully.")
            return redirect('medicalvisit:medical_visit_list')
    else:
        form = PetMedicalVisitForm(instance=medical_visit)
    
    return render(request, 'medicalvisit/medicalvisit_edit.html', {
        'form': form,
    })

@vetstaff_required
def add_medical_history(request):
    if request.method == 'POST':
        form = MedicalHistoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medicalvisit:medical_visit_list')  
    else:
        form = MedicalHistoryForm()
    
    return render(request, 'medicalvisit/add_medical_history.html', {'form': form})

medicalvisit/templates/medicalvisit/add_medical_history.html
{% extends 'core/base.html' %}

{% block title %}Add Medical history options {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-full p-16 flex justify-center bg-white">
    <div class="container w-[80%] p-6  overflow-hidden">
        <h1 class="text-2xl font-bold">Add Medical history options </h1>
        <form method="post" enctype="multipart/form-data" action="." class="p-6">
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                {% if field.errors %}
                <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                {% endif %}
            </div>
            {% endfor %}
            <div class="w-full p-4 flex flex-row justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        Submit
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

medicalvisit/templates/medicalvisit/medicalvisit_detail.html
{% extends 'core/base.html' %}

{% block content %}
<div class="w-full h-screen p-32 flex items-center justify-center bg-white">
    <div class="container p-16">
        <h1 class="p-2 text-2xl font-bold mb-2">Medical Visit Details</h1>
        <div class="p-12  overflow-hidden">
            <div class="p-4">

                <p class="p-2 text-md text-gray-700"><strong>Pet Name:</strong> {{ medical_visit.pet.name }}</p>
                <p class="p-2 text-md text-gray-700"><strong>Date of Visit:</strong> {{ medical_visit.date_of_visit|date:"Y-m-d H:i" }}</p>
                <p class="p-2 text-md text-gray-700"><strong>Symptoms:</strong> {{ medical_visit.symptoms }}</p>
                <p class="p-2 text-md text-gray-700"><strong>Diagnosis:</strong> {{ medical_visit.diagnosis }}</p>
                <p class="p-2 text-md text-gray-700"><strong>Treatment:</strong> {{ medical_visit.treatment }}</p>
                <p class="p-2 text-md text-gray-700"><strong>Vet Staff:</strong> {{ medical_visit.vet_staff.username }}
                </p>
                {% if medical_visit.notes %}
                <p class="p-2 text-md text-gray-700"><strong>Notes:</strong> {{ medical_visit.notes }}</p>
                {% endif %}
            </div>
            <!-- Links to edit and delete, if applicable -->
            {% if request.user.is_vetstaff %}
            <div class="p-4">
                <div class="flex items-center justify-center">
                    <button type="submit"
                        class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                        <span
                            class="w-60 py-1 flex flex-row justify-center items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                            <a href="{% url 'medicalvisit:edit_medical_visit' medical_visit.id %}">Edit</a>
                        </span>
                    </button>
                </div>
                <div class="p-4">
                    <div class="flex items-center justify-center">
                        <button type="submit"
                            class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row justify-center items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'medicalvisit:delete' medical_visit.id %}">Delete</a>
                            </span>
                        </button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

    {% endblock %}

medicalvisit/templates/medicalvisit/medicalvisit_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit Medical Visit{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-full p-16 flex justify-center">
    <div class="container mx-auto p-6">
        <h1 class="text-2xl font-bold mb-6">Edit Medical Visit</h1>
        <div class="max-w-md mx-auto bg-white shadow-md rounded-lg overflow-hidden md:max-w-lg">
            <form method="post" enctype="multipart/form-data" action="." class="p-6">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                    {% if field.errors %}
                    <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button type="submit"
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

medicalvisit/templates/medicalvisit/medicalvisitform.html
{% extends 'core/base.html' %}

{% block title %}Add Medical Visit{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-full p-16 flex justify-center bg-white">
    <div class="container w-[80%] p-6  overflow-hidden">
        <h1 class="text-2xl font-bold mb-6">Fill the Medical Visit Form </h1>
        <form method="post" enctype="multipart/form-data" action="." class="p-6">
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                {% if field.errors %}
                <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                {% endif %}
            </div>
            {% endfor %}
            <div class="w-full p-4 flex flex-row justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                        Submit
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

medicalvisit/templates/medicalvisit/recordsmedicalvisit.html
{% extends 'core/base.html' %}


{% block title %}Medical Visits{% endblock %}

{% block content %}
{% load custom_filters %}

<div class="w-full h-screen p-32 flex justify-center bg-white">
    <div class="container mx-auto p-6">
        <h1 class="text-2xl font-bold mb-6">Medical Visits Lists</h1>
        <div class="w-full p-4 flex flex-row justify-right">
            <button
                class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                <span
                    class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                <a href="{% url 'medicalvisit:add_medical_history' %}" class="w-full flex flex-row justify-center
                    items-center">
                    Add medical history options
                </a>
                </span>
            </button>
        </div>
        {% if medical_visits %}
        <div class="w-full flex justify-between items-center bg-gray-300">
            <div class="w-[5%] py-4 flex justify-center items-center">
                <p class="font-semibold">Pet</p>
            </div>
            <div class="w-[20%] py-4 flex justify-center items-center">
                <p class="font-semibold">Symptoms</p>
            </div>
            <div class="w-[20%] py-4 flex justify-center items-center">
                <p class="font-semibold">Diagnosis</p>
            </div>
            <div class="w-[20%] py-4 flex justify-center items-center">
                <p class="font-semibold">Treatment</p>
            </div>
            <div class="w-[10%] py-4 flex justify-center items-center">
                <p class="font-semibold">Vet Staff</p>
            </div>
            <div class="w-[15%] py-4 flex justify-center items-center">
                <p class="font-semibold">Date</p>
            </div>
        </div>
        {% for visit in medical_visits %}
        <div class="w-full flex justify-between items-center {% cycle '' 'bg-gray-100' %}">
            <div class="w-[5%] py-2 flex">
                <p class="w-full text-center">
                    <a href="{% url 'medicalvisit:medical_visit_detail'  medical_visit_id=visit.id %}">{{ visit.pet.name }}</a>
                </p>
            </div>
            <div class="w-[20%] py-2">
                <p class="w-full px-1 text-center"> {{ visit.symptoms|first_ten_words }}</p>
            </div>
            <div class="w-[20%] py-2">
                <p class="w-full px-1 text-center"> {{ visit.diagnosis|first_ten_words }}</p>
            </div>
            <div class="w-[20%] py-2">
                <p class="w-full px-1 text-center"> {{ visit.treatment|first_ten_words }}</p>
            </div>
            <div class="w-[10%] py-2">
                <p class="w-full px-1 text-justify"> {{ visit.vet_staff.username|first_ten_words }}</p>
            </div>
            <div class="w-[15%] py-2">
                <p class="w-full px-1 text-center">{{ visit.date_of_visit|date:"Y-m-d H:i" }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p class="text-gray-600 mt-6">There are no medical visits recorded yet.</p>
    {% endif %}
</div>


{% endblock %}