appointments/urls.py
from django.urls import path


from . import views

app_name = 'appointments'

urlpatterns = [
    path('add-schedule/<int:service_id>/', views.schedule_appointment_view, name='add_schedule'),
    path('cancel-appointment/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('available-slots/', views.available_slots, name='available_slots'),
    path('appointments-list/', views.view_appointments, name='appointments_list'),
    path('create-slot/', views.create_slot_view, name='create_slot'),
    path('delete-slot/<int:appointmentslot_id>/', views.delete_slots, name='delete_slot'),
    path('slots/', views.slots_view, name='slots_view'),
]

pet_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from core.views import index, about
from django.urls import path, include

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/services/', include('services.urls')),
    path('dashboard/medicalvisit/', include('medicalvisit.urls')),
    path('dashboard/appointments/', include('appointments.urls')),
    path('dashboard/chatbot/', include('chatbot.urls')),
    path('pets/', include('pets.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


   

pets/urls.py
from django.urls import path


from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.pets_list, name='list'),
    path('add-pet/', views.add_pet, name='add_pet'),
    path('<int:pet_id>/', views.pet_detail, name='detail'),
    path('<int:pet_id>/delete/', views.pet_delete, name='delete'),
    path('<int:pet_id>/edit/', views.pet_edit, name='edit'),
    path('add-weight/<int:pet_id>/', views.add_weight_record, name='add_weight_record'),
    path('<int:pet_id>/edit_goal_weight/', views.edit_goal_weight, name='edit_goal_weight'),
    path('pets/<int:record_id>/delete-weight-record/', views.delete_weight_record, name='delete_weight_record'),
    path('petowner/list/', views.petowner_list, name='petowner_list'),
    path('petowner/<int:petowner_id>/', views.petowner_detail, name='petowner_detail'),
    path('vetstaff/<int:vetstaff_id>/', views.vetstaff_detail, name='vetstaff_detail'),
    path('search/', views.search, name='search'),
    path('weight-tracker/', views.weighttracker, name='weight_tracker'),
]

services/urls.py
from django.urls import path


from . import views

app_name = 'services'

urlpatterns = [
    path('', views.service_list, name='list'),
    path('<int:pk>/', views.service_detail, name='detail'),
    path('<int:pk>/delete/', views.service_delete, name='delete'),
    path('<int:pk>/edit/', views.service_edit, name='edit'),
    path('add-service/', views.add_service, name='add_service'),
    path('create-category/', views.create_pet_service_category, name='create_category'),
    path('request-service/', views.request_service, name='request_service'),
    path('cancel/<int:request_id>/', views.cancel_service_request, name='cancel_service_request'),
    path('request-service-list/', views.request_service_list, name='request_list'),
    path('<int:request_id>/request-detail/', views.request_detail, name='request_detail'),
    path('make-payment/', views.make_payment, name='payment'),
    path('payment-successful/', views.payment_successful, name='payment_successful'),
    path('payment-cancelled/', views.payment_cancelled, name='payment_cancelled'),
    path('stripe-webhook/', views.stripe_webhook, name='stripe_webhook'),
]

services/models.py
from django.db import models
from userprofile.models import User
from pets.models import Pet


class PetServiceCategory(models.Model):
    DIAGNOSTIC = 'DIAG'
    IMAGING = 'IMG'
    VETERINARY = 'VET'
    GROOMING = 'GRO'

    CATEGORY_CHOICES = [
        (DIAGNOSTIC, 'Diagnostic'),
        (IMAGING, 'Imaging'),
        (VETERINARY, 'Veterinary Appointment'),
        (GROOMING, 'Grooming'),
    ]

    name = models.CharField(max_length=4, choices=CATEGORY_CHOICES, unique=True)

    def __str__(self):
        return self.get_name_display()


class PetService(models.Model):
    category = models.ForeignKey(PetServiceCategory, on_delete=models.CASCADE, related_name='petservices')
    name = models.CharField(max_length=100, blank=True)  
    description = models.TextField()
    cost = models.DecimalField(max_digits=10, decimal_places=2, help_text="Cost in dollars")
    duration = models.IntegerField(help_text="Duration in days")
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_services', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} - {self.category.get_name_display()}"

    

class PetRequestService(models.Model):
    petowner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, null=True, related_name='requests_services')
    service = models.ForeignKey(PetService, on_delete=models.CASCADE, null=True)
    paid = models.BooleanField(default=False, verbose_name="Paid Status")
    stripe_session_id = models.CharField(max_length=500, blank=True, null=True, verbose_name="Stripe Session ID")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.service} for {self.pet.name}"

        
class PetServiceTracker(models.Model):
    REQUESTED = 'REQUESTED'
    CONFIRMED_PAID = 'CONFIRMED_PAID'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    

    STATUS_CHOICES = [
        (REQUESTED, 'Requested'),
        (CONFIRMED_PAID, 'Confirmed Paid'),
        (IN_PROGRESS, 'In Progress'),
        (COMPLETED, 'Completed'),
        (CANCELLED, 'Cancelled'),
    ]

    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=REQUESTED)
    requested_service = models.ForeignKey(PetRequestService, on_delete=models.CASCADE, null=True, related_name='service_updates')
    is_tracked = models.BooleanField(default=False)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='service_updates')
    notes = models.TextField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='tracked_services', on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.requested_service.service.name} - {self.status}"

services/views.py
import stripe
import time
import logging
from django.conf import settings
from django.db.models import Subquery, OuterRef, Exists
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from userprofile.models import Notification, User, PetOwner
from .forms import PetServicesForm, PetRequestServicesForm, PetServiceTrackerUpdateForm, PetServiceCategoryForm
from .models import PetService, PetServiceTracker, PetRequestService

logger = logging.getLogger(__name__)


@login_required
def service_list(request):
    services = PetService.objects.all()

    return render(request, 'services/services_list.html', {
        'services': services
    })


@login_required
def service_detail(request, pk):
    service = get_object_or_404(
        PetService, created_by=request.user, pk=pk)

    return render(request, 'services/service_detail.html', {
        'service': service
    })


@login_required
def service_delete(request, pk):
    service = get_object_or_404(
        PetService, created_by=request.user, pk=pk)
    service.delete()
    messages.success(request, "The service was deleted")

    return redirect('services:list')


@login_required
def service_edit(request, pk):
    service = get_object_or_404(
       PetService, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = PetServicesForm(request.POST, instance=service)
        if form.is_valid():
            service.save()
            messages.success(request, "The service was created")

            return redirect('services:list')

    else:
        form = PetServicesForm(instance=service)

    return render(request, 'services/service_edit.html', {

        'form': form

    })

def create_pet_service_category(request):
    if request.method == 'POST':
        form = PetServiceCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            
    else:
        form = PetServiceCategoryForm()
    
    return render(request, 'services/create_category.html', {'form': form})

@login_required
def add_service(request):
    if request.method == 'POST':
        form = PetServicesForm(request.POST)

        if form.is_valid():
            service = form.save(commit=False)
            service.created_by = request.user
            service.save()
            messages.success(request, "The service was created")

            return redirect('services:list')
    else:
        form = PetServicesForm()

    return render(request, 'services/add_services.html', {

        'form': form

    })


@login_required
def request_service_list(request):
    user = request.user
    if user.is_vetstaff:
        requests_services = PetRequestService.objects.select_related('petowner').all()
    else:
        requests_services = PetRequestService.objects.filter(petowner=user)

    # Annotate with tracking information
    requests_services = requests_services.annotate(
        latest_status_update=Subquery(
            PetServiceTracker.objects.filter(
                requested_service=OuterRef('pk')
            ).order_by('-created_at').values('status')[:1]
        ),
        is_tracked=Exists(
            PetServiceTracker.objects.filter(
                requested_service=OuterRef('pk')
            )
        )
    )

    return render(request, 'services/request_list.html', {'requests_services': requests_services})


@login_required
def request_detail(request, request_id):
    user = request.user
    request_detail_qs = PetRequestService.objects.filter(id=request_id).annotate(
        latest_status_update=Subquery(
                PetServiceTracker.objects.filter(
                requested_service=OuterRef('pk')
            ).order_by('-created_at').values('status')[:1]
        )
    )
    request_detail = get_object_or_404(request_detail_qs, id=request_id)

    # Allow only the petowner who made the request or lab staff to view the details
    if not (user.is_vetstaff or request_detail.petowner == user):
        messages.error(
            request, "You do not have permission to access this request.")
        return redirect('services:dashboard')

    # Fetch all updates for the request
    updates = request_detail.service_updates.order_by('-created_at')

    # Handle status update by vet staff
    if user.is_vetstaff and request.method == 'POST':
        form = PetServiceTrackerUpdateForm(request.POST)
        if form.is_valid():
            update = form.save(commit=False)
            update.requested_service = request_detail
            update.updated_by = user
            update.save()

            Notification.objects.create(
                recipient=request_detail.petowner,
                message=f"Status of your request '{request_detail.service.name}' has been updated."
            )
            messages.success(request, "Status updated successfully.")
            return redirect('services:request_list')
    else:
        form = PetServiceTrackerUpdateForm() if user.is_vetstaff else None

    return render(request, 'services/request_detail.html', {
        'request_detail': request_detail,
        'latest_status_update': request_detail.latest_status_update,
        'updates': updates,
        'form': form,
        'paid_status': request_detail.paid,
    })

@login_required
def request_service(request):
    services = PetService.objects.all()

    if request.method == 'POST':
        form = PetRequestServicesForm(request.POST, user=request.user)
        if form.is_valid():
            service_request = form.save(commit=False)
            service_request.petowner = request.user
            service_request.save()

            # Notify staff members about the new request
            staff_members = User.objects.filter(is_vetstaff=True)
            for staff_member in staff_members:
                Notification.objects.create(
                    recipient=staff_member,
                    message=f"A new request has been made by {request.user.username}."
                )

            # Store the selected service ID for subsequent steps
            request.session['selected_service_id'] = service_request.service.id

            # Redirect to appointment scheduling
            return redirect('services:request_detail', request_id=service_request.id) 
    else:
        form = PetRequestServicesForm(user=request.user)  

    context = {
        'form': form,
        'services': services
    }
    return render(request, 'services/request_service.html', context)

@login_required
def cancel_service_request(request, request_id):
    service_request = get_object_or_404(PetRequestService, id=request_id)

    # Check if the current user is the petowner or a vet staff member
    if request.user == service_request.petowner:
        service_request.delete()
        messages.success(request, "The service request has been successfully cancelled.")
    else:
        messages.error(request, "You do not have permission to cancel this service request.")


    return redirect('services:request_list')




@login_required
def make_payment(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY

    # Retrieve or create the client profile
    petowner, created = PetOwner.objects.get_or_create(user=request.user)
    
    # Check if Stripe customer exists, create if not
    if not petowner.stripe_customer_id:
        stripe_customer = stripe.Customer.create(email=request.user.email)
        petowner.stripe_customer_id = stripe_customer.id
        petowner.save()

    # Retrieve unpaid service requests for the client
    service_requests = PetRequestService.objects.filter(petowner=request.user, paid=False).all()

    if not service_requests.exists():
        return redirect('services:request_service')

    line_items = [
    {
            'price_data': {
                'currency': 'usd',
                'product_data': {'name': service_request.service.name},
                'unit_amount': int(service_request.service.cost * 100),
            },
            'quantity': 1,
        } for service_request in service_requests
    ]


    if request.method == 'POST':
        try:
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=line_items,
                mode='payment',
                customer=petowner.stripe_customer_id,  # Use the Stripe customer ID
                success_url=request.build_absolute_uri(reverse('services:payment_successful')) + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=request.build_absolute_uri(reverse('services:payment_cancelled')),
            )
            for sr in service_requests:
                sr.stripe_session_id = checkout_session.id
                sr.save()
            return redirect(checkout_session.url, code=303)
        except stripe.error.StripeError as e:
            return HttpResponse(status=400)

    return render(request, 'services/payment.html', {
    'service_requests': service_requests,
    'total_cost': sum(sr.service.cost for sr in service_requests)
})

@login_required
def payment_successful(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session_id = request.GET.get('session_id', None)
    session = stripe.checkout.Session.retrieve(checkout_session_id)
    customer = stripe.Customer.retrieve(session.customer)
    user_id = request.user.id 
    petowner = PetOwner.objects.get(user=request.user)
    petowner.stripe_checkout_id = checkout_session_id
    petowner.save()

    return render(request, 'services/payment_successfull.html', {'customer': customer})

@login_required
def payment_cancelled(request):
    return render(request, 'services/payment_cancelled.html')

@csrf_exempt
def stripe_webhook(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY

services/templates/services/create_category.html
{% extends 'core/base.html' %}

{% block title %} My pet app {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-screen p-16 flex justify-center  bg-white">
    <div class="container w-[60%] p-6 px-8 pt-6 pb-8 mb-4">
        <h1 class="text-2xl font-bold mb-4">Add Category Service</h1>

        <form method="post" enctype="multipart/form-data" action="." class="p-6">
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                {% if field.errors %}
                <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                {% endif %}
            </div>
            {% endfor %}
            <div class="w-full p-4 flex flex-row justify-center">
                <button
                    class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                    <span
                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                            Add Category
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>



{% endblock %}

services/templates/services/payment_cancelled.html
{% extends 'core/base.html' %}

{% block title %}payment cancelled{% endblock %}

{% block content %}
<div class="w-full h-full p-16 flex justify-center">
    <div class="container home_msg mx-auto p-4">
        <h1 class="text-xl mb-4">Your payment didnt go through </h1>
    </div>
</div>

{% endblock %}

services/templates/services/request_detail.html
{% extends 'core/base.html' %}

{% block title %} Request Detail - {{ request_detail.petowner.username }} {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="w-full h-full relative flex flex-col pt-16 pb-16 items-center justify-start bg-white">
    <div
        class="container w-full h-full flex flex-col lg:flex-row items-center justify-center">
        <div class="w-full lg:w-[65%] h-full lg:pr-2 lg:pb-0 flex flex-col">
            <div class="w-full  h-[750px] lg:h-1/2 p-2 flex">
                <div class="w-full p-4 flex flex-col bg-white items-center">
                    <h1 class="w-full flex text-xl font-bold p-4">Request Detail for {{ request_detail.petowner.first_name }} {{ request_detail.petowner.last_name }}</h1>
                    <div class="w-full flex flex-col p-4">
                        <h2 class="text-lg font-semibold p-1">Pet: {{ request_detail.pet.name }}</h2>
                    </div>
                    <div class="w-full flex flex-col p-4">
                        {% if request_detail.service %}
                        <div class="w-full flex flex-row items-center p-2">
                            <p class="text-lg font-semibold">Service:
                            </p>
                            <h5 class="flex w-full px-1 text-center">{{ request_detail.service.name }}</h5>
                        </div>
                        <div class="w-full flex flex-row items-center p-2">
                            <p class="text-lg font-semibold">Cos:
                            </p>
                            <h5 class="flex w-full px-1 text-center">{{ request_detail.service.cost }}$</h5>
                        </div>

                        <div class="w-full flex flex-row p-2">
                            <p class="text-lg font-semibold">Description:
                            </p>
                            <h5 class="px-2 text-left">{{ request_detail.service.description }}</h5>
                        </div>
                        <div class="w-full flex flex-row items-center p-2">
                            {% endif %}
                            <p class="text-lg font-semibold">
                                Payment Status:
                                {% if request_detail.paid %}
                                Paid
                                {% else %}
                                Not Paid
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <div class="w-full flex flex-row items-center p-4">
                        <p class="text-lg font-semibold pr-4">Latest Status: </p>
                        {% if request_detail.latest_status_update %}
                        <p class="text-gray-700"> {{ request_detail.latest_status_update }} </p>
                        {% else %}
                        <p class="text-gray-500"> No status updates available. </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="w-full h-[250px] lg:h-1/2 p-2 flex">
                <div class="w-full p-4 flex flex-col bg-white items-center">
                    {% if request.user.is_vetstaff %}
                    <h2 class="flex text-lg font-semibold">Update Status</h2>
                    <div class="flex">
                        <form method="post" enctype="multipart/form-data" action="." class="p-4">
                            {% csrf_token %}

                            {% for field in form %}
                            <div class="p-2">
                                <label class="block text-gray-700 text-sm font-bold" for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                </label>
                                {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                                {% if field.errors %}
                                <p class="text-red-500 text-xs italic">{{ field.errors }}</p>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="w-full p-4 flex flex-row justify-center">
                                <button
                                    class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                                    <span
                                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                        Update Status
                                    </span>
                                </button>
                            </div>
                        </form>
                    </div>
                    {% else %}
                    <div class="flex">
                        <div class="flex p-2 items-center">
                            <form action="{% url 'services:cancel_service_request' request_detail.id %}" method="post"
                                class="mb-2">
                                {% csrf_token %}
                                <button
                                    class="h-fit p-[2px] flex flex-row items-center font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                                    <span
                                        class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                        Cancel Request
                                    </span>
                                </button>
                            </form>
                        </div>
                        <div class="flex p-2">
                            <button
                                class="h-fit p-[2px] flex flex-row items-center justify-end  font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                                <span
                                    class="w-60 py-1 flex flex-row items-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                    <a href="{% url 'appointments:add_schedule' request_detail.id %}" class="w-full flex flex-row justify-center
                                                                    items-center">
                                        Schedule Appointment
                                    </a>
                                </span>
                            </button>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w-full lg:w-[35%] h-full lg:pl-2 pt-2 lg:pt-0 flex flex-col">
            <div class="w-full h-[170px] lg:h-1/2 p-4 flex flex-col bg-white">
                <h2 class="flex text-lg font-semibold mb-3 w-full px-1 text-center text-justify">Updates History</h2>
                {% for update in updates %}
                <div class="mb-2 mt-2 flex flex-col justify-center py-2">
                    <p class="w-full px-1 text-center text-justify">Status: {{ update.get_status_display }}</p>
                    <p class="w-full px-1 text-center text-justify">Note: {{ update.notes }}</p>
                    <p class="w-full px-1 text-center text-justify">Updated by: {{ update.updated_by.username }}</p>
                    <p class="w-full px-1 text-center text-justify">Updated at: {{ update.created_at }}</p>
                </div>
                {% empty %}
                <p class="flex text-gray-500">No updates have been made for this request.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>








{% endblock %}

services/templates/services/service_detail.html
{% extends 'core/base.html' %}

{% block title %} {{ service.name}} {% endblock %}

{% block content %}
<div class="w-full h-screen relative flex flex-col pt-32 pb-16 items-center justify-start bg-white">
    <div class="container w-full h-full flex flex-col lg:flex-row items-center justify-center">
        <div class="w-full lg:w-[65%] h-full lg:pr-2 lg:pb-0 p-6 flex flex-col">
            <div class="w-full flex flex-col">
                <h1 class="mb-4 text-xl">{{ service.name}}</h1>
            </div>
            {% if service.description %}
            <div class="w-full flex flex-row p-2">
                <p class="flex font-semibold pr-2">Description:</p>
                <h5 class="flex mb-2 text-xl">{{ service.description }}</h5>
            </div>
            <div class="w-full flex flex-row p-2">
                <p class="flex font-semibold pr-2">Cost:</p>
                <h5 class="flex mb-2 text-xl">{{ service.cost }} $</h5>
            </div>

            <div class="w-full flex flex-row p-2">
                <p class="flex font-semibold pr-2">Duration:</p>
                <h5 class="flex mb-2 text-xl">{{ service.duration }} day</h5>
            </div>
            {% endif %}
            <div class="w-full flex flex-row p-2">
                <p class="flex font-semibold pr-2">Created by:</p>
                <h5 class="flex mb-2 text-xl">{{ service.name.created_by }}</h5>
            </div>
            <div class="w-full flex flex-row pr-6 items-center">
                <div class="w-full flex flex-col">
                    <div class="w-full p-4 flex flex-row justify-center">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'services:edit' service.id %}" class="w-full flex flex-row justify-center
                            items-center">
                                    Edit
                                </a>
                            </span>
                        </button>
                    </div>
                    <div class="w-full p-4 flex flex-row justify-center">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'services:list' %}" class="w-full flex flex-row justify-center
                            items-center">
                                    Back to
                                    Services
                                </a>
                            </span>
                        </button>
                    </div>
                </div>
                <div class="w-full flex flex-col">
                    <div class="w-full p-4 flex flex-row justify-center">
                        <button
                            class="h-fit p-[2px] flex flex-row items-center justify-center text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-500 to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200">
                            <span
                                class="w-60 py-1 flex flex-row items-center justify-center rounded-md bg-white hover:bg-opacity-0 transition-all ease-in duration-75">
                                <a href="{% url 'services:delete' service.id %}" class="w-full flex flex-row justify-center
                            items-center">
                                    Delete
                                </a>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}